version: "3.9"

services:
  test:
    image: python:3.12.0a4-alpine3.17
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/automation
    command: /bib/sh -c "ls -la && pytest -m health --alluredir=allure-results"